site_name: KickCraft Wiki
repo_url: https://github.com/Landon-9999/kickcraft
repo_name: KickCraft Public Repo
edit_uri: edit/main/docs/

plugins:
  - blog
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

markdown_extensions:
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr

# Page tree
nav:
  - Home: index.md
  - Discord Rules: discord-rules.md
  - MC Server Rules: mc-rules.md
  - Blog:
    - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/kickcraftsmp
      name: KickCraft Discord
    - icon: simple/kick
      link: https://kick.com/
      name: Kick
    - icon: logos/nodecraft-logogram
      link: https://nodecraft.com/r/kickcraft
      name: Brought to you by Nodecraft!

theme:
  name: material
  font:
    text: Quicksand
  features:
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.prune
    - toc.follow
    - content.action.edit
    - content.tooltips
  custom_dir: overrides
  favicon: images/logo.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        primary: green

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: indigo

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: green
      accent: amber