site_name: KickCraft Wiki
repo_url: https://github.com/Landon-9999/kickcraft
repo_name: KickCraft Public Repo
edit_uri: edit/main/docs/

plugins:
  - blog
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

markdown_extensions:
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/kickcraftsmp
      name: KickCraft Discord
    - icon: material/image-off
      link: https://nodecraft.com
      name: Nodecraft

theme:
  name: material
  font:
    text: Quicksand
  logo: images/logo.png
  features:
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.prune
    - toc.follow
    - content.action.edit
    - content.tooltips


  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        primary: green

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: indigo

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: green
      accent: amber

