name: Bug report
description: Use this to report bugs!
title: '[Bug]: '
labels:
  - Bug
  - Needs Triage
projects:
  - KickCraft/3
body:
  - type: dropdown
    id: env
    attributes:
      label: Where is the bug?
      options:
        - MC Server
        - Wiki
        - Discord
        - Modpack
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: This may include a build schematic, a video/stream, or detailed instructions to help reconstruct the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Before submitting this issue, please ensure the following:

        1. If you are using the modpack: You are running the latest version of the modpack from [our downloads page](https://modrinth.com/modpack/kickcraft/versions).
        2. You searched for and ensured there isn't already an open issue regarding this.

        If you think you have a bug but are not sure, open a ticket with us in the `#submit-a-ticket` channel of our
        [Discord](https://discord.gg/kickcraftsmp).