
name: Bug report
description: Use this template to report bugs!
title: '[Bug]: '
labels:
  - Bug
  - Needs Triage
projects:
  - KickCraft/3
body:
  - type: dropdown
    id: env
    attributes:
      label: Where is the bug?
      options:
        - MC Server
        - Wiki
        - Discord
        - Modpack
    validations:
      required: true
  - type: input
    id: affect
    attributes:
      label: Who does this affect?
      description: Just you, a few people, or everyone?
      placeholder: Everyone is affected by this bug because...
    validations:
      required: true
