authors:
  landon:
    name: Landon
    description: Lead Developer<br><strong>Tech Team</strong>
    avatar: https://avatars.githubusercontent.com/u/109770546?v=4
  rosy:
    name: Rosy Skies
    description: Lead Admin<br><strong>Admin Team</strong>
    avatar: https://avatars.githubusercontent.com/u/157574799?v=4